env: "gymma"

env_args:
  key: null
  time_limit: 300
  pretrained_wrapper: null
  visdom: False  
  sumo_headless: False
  sumo_port: 45761
  scenarios: "intersections/4lane_merge"
  headless: True
  num_external_sumo_clients: 0
  shuffle_scenarios: False

  agent_specs:
    agent_builder: LaneAgent
    agent_interface:
      agent_type: Laner
      neighbourhood_vehicle_radius: 1000
      accelerometer: True 
      max_episode_steps: 300  
  env_info:
    n_agents: 4
    n_actions: 4
    n_pixels: 112  #112*112*3
    state_shape: 
    episode_limit: 1000
    name: intersection_merge
    

buffer_size: 10
batch_size: 2
save_model: False # Save the models to disk
save_model_interval: 50000
evaluate: False 
use_tensorboard: False 
test_greedy: True
test_nepisode: 5
test_interval: 50000
log_interval: 1000
runner_log_interval: 1000
learner_log_interval: 1000
t_max: 2050000
